root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/worker ./cmd/worker"
bin = "./tmp/worker"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "frontend"]

[log]
time = true
