FROM golang:alpine

WORKDIR /app

# Install git, build-base, and air for hot reloading
RUN apk add --no-cache git build-base && \
    go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["air", "-c", ".air.worker.toml"]
